#include <iostream>
#include "Instructor.h"




Instructor::Instructor(): Person(), salary(0)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000894 begin
{
}
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000894 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Instructor::Instructor(string n, string d, string g, int s): Person(n, d, g), salary(s)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000896 begin
{
}
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000896 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Instructor::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000898 begin
{
    if (gender == "M")
        cout << "Mr. ";
    else // assuming gender == "F"
        cout << "Ms. ";
    Person::print();
    cout << "    Instructor, Salary: " << salary << endl;
}
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000898 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
