#include <iostream>
#include <string>
#include "Person.h"




Person::Person():name(""), dob(""), gender("")
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000881 begin
{
}
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000881 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person::Person(string n, string d, string g):name(n), dob(d), gender(g)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000883 begin
{
}
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000883 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Person::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000888 begin
{
    cout << name << " " << dob << endl;
}
// section -117--74--108-95-474f0f0b:16197a0a05c:-8000:0000000000000888 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
